# Generated by Django 2.2.7 on 2019-11-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('a1', models.CharField(max_length=100)),
                ('a2', models.CharField(max_length=100)),
                ('a3', models.CharField(max_length=100)),
                ('a4', models.CharField(max_length=100)),
                ('right', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
            ],
        ),
    ]
